declare module 'underscore.string' {
  export function humanize(str: string): string;
  export function slugify(str: string): string;
  export function camelize(str: string): string;
  export function capitalize(str: string): string;
  export function decapitalize(str: string): string;
  export function dasherize(str: string): string;
  export function underscored(str: string): string;
  export function classify(str: string): string;
  export function titleize(str: string): string;
  export function trim(str: string, characters?: string): string;
  export function ltrim(str: string, characters?: string): string;
  export function rtrim(str: string, characters?: string): string;
  export function truncate(str: string, length: number, truncateStr?: string): string;
  export function prune(str: string, length: number, pruneStr?: string): string;
  export function words(str: string, delimiter?: string | RegExp): string[];
  export function pad(str: string, length: number, padStr?: string, type?: 'left'|'right'|'both'): string;
  export function lpad(str: string, length: number, padStr?: string): string;
  export function rpad(str: string, length: number, padStr?: string): string;
  export function lrpad(str: string, length: number, padStr?: string): string;
  export function sprintf(format: string, ...args: any[]): string;
  export function vsprintf(format: string, args: any[]): string;
  export function toNumber(str: string, decimals?: number): number;
  export function strRight(str: string, sep: string): string;
  export function strRightBack(str: string, sep: string): string;
  export function strLeft(str: string, sep: string): string;
  export function strLeftBack(str: string, sep: string): string;
  export function stripTags(str: string): string;
  export function surround(str: string, wrapper: string): string;
  export function quote(str: string, quoteChar?: string): string;
  export function unquote(str: string, quoteChar?: string): string;
  export function repeat(str: string, qty: number, separator?: string): string;
  export function naturalCmp(str1: string, str2: string): number;
  export function toBoolean(str: string, trueValues?: string[], falseValues?: string[]): boolean;
  export function clean(str: string): string;
  export function chars(str: string): string[];
  export function swapCase(str: string): string;
  export function escapeHTML(str: string): string;
  export function unescapeHTML(str: string): string;
  export function escapeRegExp(str: string): string;
  export function splice(str: string, i: number, howmany: number, substr?: string): string;
  export function insert(str: string, i: number, substr: string): string;
  export function include(str: string, needle: string): boolean;
  export function count(str: string, substr: string): number;
  export function reverse(str: string): string;
  export function startsWith(str: string, starts: string, position?: number): boolean;
  export function endsWith(str: string, ends: string, position?: number): boolean;
  export function pred(str: string): string;
  export function succ(str: string): string;
  export function titleCase(str: string): string;
  export function join(separator: string, ...args: any[]): string;
  export function lines(str: string): string[];
  export function dedent(str: string, pattern?: string): string;
  export function wrap(str: string, options?: number | { width?: number; separator?: string; cut?: boolean; preserveSpaces?: boolean; trailingSpaces?: boolean }): string;
}
